### ISSUE TITLE
google play music

### ISSUE THREAD

**Issue by Soneji** [Sumanthnr93/googleassistant#1]
Hey dude, this isnt really an issue, but more of a question. I was wondering how exactly you got google play music working on ubuntu? I have managed to set up the assistant sample on my laptop running Arch Linux, and I would love to know how you managed to get music playing. :)

**Comment by sumanthExp** [comment]
Sorry about this really late reply. I was not much on github. I used Selenium to setup which is not at all efficient. But I believe you can get api for any music library which you can use.
